package com.programbao.vlc_video;

// Source code is unavailable, and was generated by the Fernflower decompiler.

import static android.view.View.GONE;
import static android.view.View.INVISIBLE;
import static android.view.View.VISIBLE;

import android.animation.ObjectAnimator;
import android.animation.ValueAnimator;
import android.app.Activity;
import android.content.Context;
import android.content.pm.ActivityInfo;
import android.net.Uri;
import android.os.Build;
import android.os.Handler;
import android.os.Message;
import android.util.DisplayMetrics;
import android.util.Log;
import android.view.MotionEvent;
import android.view.OrientationEventListener;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import android.widget.TextView;

import com.alibaba.fastjson.JSONObject;
import com.programbao.vlc_video.util.EnumConfig;
import com.programbao.vlc_video.util.MediaListenerEvent;
import com.taobao.weex.WXSDKInstance;
import com.taobao.weex.annotation.JSMethod;
import com.taobao.weex.bridge.JSCallback;
import com.taobao.weex.ui.action.BasicComponentData;
import com.taobao.weex.ui.component.WXComponent;
import com.taobao.weex.ui.component.WXComponentProp;
import com.taobao.weex.ui.component.WXVContainer;

//import org.videolan.libvlc.IVLCVout;
import org.videolan.libvlc.LibVLC;
import org.videolan.libvlc.Media;
import org.videolan.libvlc.MediaPlayer;
import org.videolan.libvlc.interfaces.IVLCVout;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import io.dcloud.feature.uniapp.annotation.UniJSMethod;

//import javax.naming.Context;

public class VlcVideoV2 extends WXComponent<RelativeLayout> {
    private String TAG = "VlcVideo";
    private LibVLC mLibVLC;
    private MediaPlayer mMediaPlayer;

    private SurfaceView surfaceView;

    private RelativeLayout vlcContainerView;

    RelativeLayout mRootView;

    /*顶部控件*/
    private LinearLayout mControlTopLayout;
    /*底部控件*/
    private RelativeLayout mControlBottomLayout;
    /*右边控件*/
    private LinearLayout mControlRightLayout;
    /*中间倍速选择控件*/
    private LinearLayout mControlMiddleSpeedLayout;
    /*中间状态控件*/
    private LinearLayout mControlMiddleStatusLayout;
    /*倍速控件*/
    private TextView mSpeedBtn;
    /*倍速选择组控件*/
    private RadioGroup radioGroupView;

    /*顶部返回控件*/
    private ImageView mTopBack;
    /*标题*/
    private TextView mTopTitle;
    /*时间文本*/
    private TextView vlcDuration;
    /*进度条*/
    private SeekBar vlcSeekbar;
    /*加载loading*/
    private ENDownloadView mVlvLoadingView;
    /*错误信息*/
    private TextView mVlvErrorTextView;
    public String mTitle = "我是标题";

    private ImageView mPlayBtn;

    private String currentPlayProtocol;
    private String currentPlayUrl;


    private IVLCVout vlcVout;
    Activity activity; // 在初始化时传入

    private boolean isFullscreen = false; // 标记是否处于全屏模式
    private boolean isPlay = false; // 标记是否处于播放

    private boolean isFirstPlay = true; //  是否是第一次播放
    private boolean isShowMiddleSelectSpeed = false; // 标记是否处于倍速控件选择
    private int seekStartProgress; // 记录拖动开始时的进度

    private int initVideoHeight;
    ImageView fullControl;
    private OrientationEventListener orientationEventListener;  // 横竖屏变化事件监听

    public VlcVideoV2(WXSDKInstance instance, WXVContainer parent, BasicComponentData basicComponentData) {
        super(instance, parent, basicComponentData);
        activity = (Activity) instance.getContext();
    }

    @Override
    protected RelativeLayout initComponentHostView(Context context) {
        initPlay(context);
        // 添加返回键事件监听器
//        vlcContainerView.setFocusableInTouchMode(true);
//        vlcContainerView.requestFocus();
//        vlcContainerView.setOnKeyListener(this);
        return mRootView;
    }


    public void initPlay(Context context) {
        ArrayList localObject = new ArrayList();
        localObject.add("-vvv");
        localObject.add("--no-drop-late-frames");
        localObject.add("--no-skip-frames");
        localObject.add("--rtsp-tcp");
        localObject.add("--avcodec-hw=any");
        localObject.add("--live-caching=0");
//        /正式参数配置
        //值越大，缓存越大，延迟越大。这三项是延迟设置
        localObject.add(":clock-jitter=0");
        localObject.add(":clock-synchro=0");
//        涉及延迟的参数有：network-caching（网络缓存）、live-caching（直播缓存）、file-caching（文件缓存）、sout-mux-caching（输出缓存）。
        localObject.add("--rtsp-caching=500");//
        localObject.add("--tcp-caching=500");//TCP输入缓存值 (毫秒)
        localObject.add("--realrtsp-caching=500");//RTSP缓存值 (毫秒)
        localObject.add("--network-caching=500");//网络缓存
        localObject.add(":live-caching=500");//直播缓存
        localObject.add(":file-caching=500");//文件缓存
        localObject.add("--file-caching");//文件缓存
        localObject.add("--sout-mux-caching=500");//输出缓存
        localObject.add("--no-drop-late-frames");//关闭丢弃晚的帧 (默认打开)
        localObject.add("--no-skip-frames");//关闭跳过帧 (默认打开)
        localObject.add(":rtsp-frame-buffer-size=500"); //RTSP帧缓冲大小，默认大小为100000
        localObject.add("--rtsp-tcp");
        localObject.add("--http-reconnect");    //: 重连
        localObject.add("--deinterlace");    //: 交错
//        localObject.add("" + getDeblocking(-1));//这里太大了消耗性能   太小了会花屏
        localObject.add("--deinterlace-mode={discard,blend,mean,bob,linear,x}");// 视频译码器 解除交错模式
        localObject.add("--network-synchronisation");// 网络同步化 (默认关闭)

        mLibVLC = new LibVLC(context, localObject);
        mMediaPlayer = new MediaPlayer(mLibVLC);
        System.out.println("mLibVLCmLibVLCmLibVLCmLibVLC");
        VlcVideoView vlcVideoView = new VlcVideoView(context);

        /*获取布局元素*/
        surfaceView = vlcVideoView.getVideoView();
        vlcContainerView = vlcVideoView.getVlcContainerView();
        mRootView = vlcVideoView.getmRootView();
        mControlTopLayout = vlcVideoView.getmControlTopLayout();
        mControlBottomLayout = vlcVideoView.getmControlBottomLayout();
        mControlRightLayout = vlcVideoView.getmControlRightLayout();
        mControlMiddleSpeedLayout = vlcVideoView.getmControlMiddleSpeedLayout();
        mControlMiddleStatusLayout = vlcVideoView.getmControlMiddleStatusLayout();
        mTopBack = vlcVideoView.getmTopBack();
        mTopTitle = vlcVideoView.getmTopTitle();
        mPlayBtn = vlcVideoView.getmPlayBtn();
        vlcDuration = vlcVideoView.getVlcDuration();
        vlcSeekbar = vlcVideoView.getVlcSeekbar();
        fullControl = vlcVideoView.getFullControll();
        mSpeedBtn = vlcVideoView.getmSpeedBtn();
        radioGroupView = vlcVideoView.getRadioGroupView();
        mVlvLoadingView = vlcVideoView.getmVlvLoadingView();
        mVlvErrorTextView = vlcVideoView.getmVlvErrorTextView();


        vlcVout = mMediaPlayer.getVLCVout();


        // 设置各种控件状态
        /*默认隐藏*/
        mTopBack.setVisibility(GONE);
        mControlMiddleSpeedLayout.setVisibility(GONE);
        mRootView.setOnTouchListener(new OnDoubleClickListener(mMediaPlayer, new OnDoubleClickListener.DoubleClickCallback() {
            @Override
            public void onDoubleClick() {
                handlePlay();//处理双击事件
            }

            @Override
            public void onClick() {
                // 先移除之前发送的
                mRootView.removeCallbacks(mShowControllerRunnable);
                mRootView.removeCallbacks(mHideControllerRunnable);
                if (mControllerShow) {
                    // 隐藏控制面板
                    mRootView.post(mHideControllerRunnable);
                } else {
                    // 显示控制面板
                    mRootView.post(mShowControllerRunnable);
                    mRootView.postDelayed(mHideControllerRunnable, 5000);
                }
            }

            @Override
            public void onTouch(View v, MotionEvent event, float touchStartX, long startPosition) {
//                System.out.println("mMediaPlayer.getTime() --" + mMediaPlayer.getTime() + "mMediaPlayer.getLength()--"+mMediaPlayer.getLength());
//                touchStartX = event.getX();
                System.out.println("event.getAction() --- " + event.getAction());
                float touchEndX = event.getX();
                float deltaX = touchEndX - touchStartX;
                // 根据滑动的距离来调整时间
                long newPosition = startPosition + (long) (deltaX * mMediaPlayer.getLength() / v.getWidth()) / 10;
                if (newPosition < 0) {
                    newPosition = 0;
                }
                if (newPosition > mMediaPlayer.getLength()) {
                    newPosition = mMediaPlayer.getLength();
                }
                // 更新进度条位置
                vlcSeekbar.setProgress((int) (newPosition * 100 / mMediaPlayer.getLength()));
                // 更新电影对象的位置
                mMediaPlayer.setTime(newPosition);
            }
        }));


        /*播放控件点击*/
        mPlayBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                handlePlay();
            }
        });

        /*全屏控件点击事件*/
        fullControl.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // 在按钮点击时执行的代码
                // 例如：处理按钮点击事件
                handleFullScreenStatus();
            }
        });
        /*顶部返回控件点击事件*/
        mTopBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (isFullscreen) exitFullScreen(null, null);
            }
        });
        /*进度条控件改变事件*/
        vlcSeekbar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int i, boolean b) {
                Log.v("NEW POS", "pos is ----  : " + i);
//                if (i != 0)
//                    mMediaPlayer.setPosition(((float) i / 100.0f));
            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
// 拖动开始时记录当前进度
                seekStartProgress = vlcSeekbar.getProgress();
            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
                // 拖动结束时计算拖动的距离，并设置播放进度
                int seekEndProgress = vlcSeekbar.getProgress();
                int deltaProgress = seekEndProgress - seekStartProgress;

                // 计算拖动的百分比
                float deltaPercentage = (float) deltaProgress / vlcSeekbar.getMax();

                // 获取当前播放器的位置
                float currentPosition = mMediaPlayer.getPosition();

                // 计算新的位置
                float newPosition = currentPosition + deltaPercentage;

                // 确保新位置在合法范围内
                newPosition = Math.max(0.0f, Math.min(1.0f, newPosition));

                // 设置新的播放进度
                mMediaPlayer.setPosition(newPosition);
            }
        });
        /*倍速控件点击*/
        mSpeedBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                /*显示中间倍速选择控件*/
                if (isShowMiddleSelectSpeed) {
                    mControlMiddleSpeedLayout.setVisibility(GONE);
                    isShowMiddleSelectSpeed = false;
                } else {
                    mControlMiddleSpeedLayout.setVisibility(VISIBLE);
                    isShowMiddleSelectSpeed = true;
                }
            }
        });
        radioGroupView.setOnCheckedChangeListener(new RadioGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(RadioGroup group, int checkedId) {
                // 在这里处理选中的RadioButton变化
                if (checkedId == R.id.radioButton1) {// 选中了0.5x，执行相应的操作，例如更改播放速度
                    mSpeedBtn.setText("0.5x");
                    mMediaPlayer.setRate(0.5f);
                } else if (checkedId == R.id.radioButton2) {// 选中了1.0x，执行相应的操作
                    mSpeedBtn.setText("1.0x");
                    mMediaPlayer.setRate(1.0f);
                } else if (checkedId == R.id.radioButton3) {// 选中了1.25x，执行相应的操作
                    mSpeedBtn.setText("1.25x");
                    mMediaPlayer.setRate(1.25f);
                } else if (checkedId == R.id.radioButton4) {// 选中了1.5x，执行相应的操作
                    mSpeedBtn.setText("1.5x");
                    mMediaPlayer.setRate(1.5f);
                } else if (checkedId == R.id.radioButton5) {// 选中了2.0x，执行相应的操作
                    mSpeedBtn.setText("2.0x");
                    mMediaPlayer.setRate(2.0f);
                }
            }
        });


        mMediaPlayer.setEventListener(new MediaPlayer.EventListener() {
            @Override
            public void onEvent(MediaPlayer.Event event) {
                // 处理播放事件
                videoPlayerEvent(event);
            }
        });
        /*视频视图变化监听*/
        setMediaListenerEvent();

    }

    private MediaListenerEvent mediaListenerEvent;
    public void setMediaListenerEvent() {
        this.mediaListenerEvent = new MediaListenerEvent() {
            @Override
            public void eventBuffing(int event, float buffing) {
                if (buffing < 100) {
//                    mPlayStatueType = EnumConfig.PlayState.STATE_LOAD;
                    if (mVlvLoadingView.getVisibility() == VISIBLE) {
                        return;
                    }
                    handlerMsgShowHidePlayLoadingView(EnumConfig.PlayerState.PLAYER_SHOW_LOADING_VIEW);
                    //缓冲时不允许手势操作
//                    mPlayerView.setGestureEnable(false);
                } else if (buffing == 100) {
//                    mPlayerView.setGestureEnable(true);
//                    mPlayStatueType = EnumConfig.PlayState.STATE_PLAY;
                    handlerMsgShowHidePlayLoadingView(EnumConfig.PlayerState.PLAYER_HIDE_LOADING_PLAY_VIEW);

                }
            }

            @Override
            public void eventStop(boolean isPlayError) {
//                if (null != mPlayerTimeDis) {
//                    mPlayerTimeDis.dispose();
//                    mPlayerTimeDis = null;
//                }
//                mPlayStatueType = EnumConfig.PlayState.STATE_STOP;
                handlerMsgShowHidePlayLoadingView(EnumConfig.PlayerState.PLAYER_SHOW_ERROR_VIEW);

            }

            @Override
            public void eventError(int event, boolean show) {
//                mPlayStatueType = EnumConfig.PlayState.STATE_STOP;
                handlerMsgShowHidePlayLoadingView(EnumConfig.PlayerState.PLAYER_SHOW_ERROR_VIEW);

            }

            @Override
            public void eventPlay(boolean isPlaying) {
                if (isPlaying) {
//                    createPlayerTimeSub();
                }
            }

            @Override
            public void eventSystemEnd(String isStringed) {

            }

            @Override
            public void eventCurrentTime(String time) {

            }

            @Override
            public void eventPlayInit(boolean openClose) {//openClose 当前界面是否可见,推入后台,就是不可见=false


            }
        };
    }
    private void handlerMsgShowHidePlayLoadingView(int toastStr) {
//        Message tempMsg = mHandler.obtainMessage();
//        tempMsg.what = SHOW_HIDE_PLAYER_VIEW;
//        tempMsg.obj = toastStr;
//        mHandler.sendMessageDelayed(tempMsg, SHOW_HIDE_PLAYER_VIEW);
        showHidePlayLoadingView(toastStr);
    }

    /**
     * 显示或者隐藏 加载/开始 View
     *
     * @param type 传入需要显示View的类型
     */
    public void showHidePlayLoadingView(int type) {
        //显示loadingView,隐藏playView
        if (EnumConfig.PlayerState.PLAYER_SHOW_LOADING_VIEW == type) {
            mVlvLoadingView.setVisibility(View.VISIBLE);
//            mVlvPlayView.setVisibility(INVISIBLE);
            mVlvErrorTextView.setVisibility(INVISIBLE);
            mVlvLoadingView.start();
        } else if (EnumConfig.PlayerState.PLAYER_SHOW_PLAY_VIEW == type) {
//            mVlvPlayView.setVisibility(VISIBLE);
            mVlvLoadingView.setVisibility(INVISIBLE);
            mVlvErrorTextView.setVisibility(INVISIBLE);
            mVlvLoadingView.release();
        } else if (EnumConfig.PlayerState.PLAYER_HIDE_LOADING_PLAY_VIEW == type) {
            //全部隐藏
            mVlvLoadingView.release();
//            mVlvPlayView.setVisibility(INVISIBLE);
            mVlvLoadingView.setVisibility(INVISIBLE);
            mVlvErrorTextView.setVisibility(INVISIBLE);
        } else if (EnumConfig.PlayerState.PLAYER_SHOW_ERROR_VIEW == type) {
            //显示错误文字和加载view
            mVlvLoadingView.release();
            mVlvLoadingView.setVisibility(INVISIBLE);
//            mVlvPlayView.setVisibility(VISIBLE);
            mVlvErrorTextView.setVisibility(VISIBLE);
        }

    }




    @WXComponentProp(name = "play")
    public void play(String path) throws MalformedURLException {
        URL url = new URL(path);
//        String protocol = url.getProtocol(); // 获取协议
//        if(currentPlayProtocol != null && !currentPlayProtocol.equals(protocol)) {
//            // 协议不同,不执行播放
//            return;
//        }
//        currentPlayProtocol = protocol;

        if(currentPlayUrl != null && currentPlayUrl.equals(url)) {
            // 播放链接相同,不执行播放
            return;
        }
        currentPlayUrl = String.valueOf(url);
        mMediaPlayer.stop();
        vlcVout.detachViews();
        surfaceView.post(new Runnable() {
            @Override
            public void run() {
                // 在子线程中准备播放
                int width = surfaceView.getWidth();
                int height = surfaceView.getHeight();
//                if (width <= 0) {
//                    width = 1080;
//                }
                System.out.println("width:" + width + " height:" + height);
                int initVideoHeight = height;
                vlcVout.setWindowSize(width, height);
                vlcVout.setVideoSurface(surfaceView.getHolder().getSurface(), surfaceView.getHolder());
                vlcVout.attachViews();
                try {
                    Media media = new Media(mLibVLC, Uri.parse(path));
                    media.setHWDecoderEnabled(true, false);
                    media.addOption(":network-caching=100");
                    media.addOption(":clock-jitter=0");
                    media.addOption(":clock-synchro=0");
                    media.addOption(":fullscreen");
                    mMediaPlayer.setAspectRatio(width + ":" + height);
                    mMediaPlayer.setMedia(media);
                    media.release();
                } catch (Exception var4) {
                    throw new RuntimeException("Invalid asset folder");
                }
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        vlcContainerView.postDelayed(mHideControllerRunnable, 5000);
                    }
                }, 3000); // 3秒delay
                /*设置总时长*/
                vlcDuration.setText("00:00:00 / 未播放");
                /*自动播放*/
//                mMediaPlayer.play();
//                mPlayBtn.setImageResource(R.drawable.player_pause);
                mPlayBtn.setImageResource(R.drawable.player_play);
                if (!isFirstPlay) {
                    mMediaPlayer.play();
                    mPlayBtn.setImageResource(R.drawable.player_pause);
                    isPlay = true;
                }
                /*屏幕常亮*/
                activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
                /*关闭常亮*/
                // activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }
        });
    }
    @WXComponentProp(name = "title")
    public void setVideoTitle(String title) {
        mTitle = title;
        mTopTitle.setText(mTitle + "");
    }



    public void handlePlay() {
        if (isPlay) {
            pause(null, null);
            mPlayBtn.setImageResource(R.drawable.player_play);
        } else {
            toPlay();
            mPlayBtn.setImageResource(R.drawable.player_pause);
        }
    };

    /*处理是否进入或退出全屏*/
    public void handleFullScreenStatus() {
        if (isFullscreen) {
            exitFullScreen(null, null);
        } else {
            enterFullScreen(null, null);
        }
    }

    @JSMethod
    public void handleIsExitFullScreenStatus(JSCallback callback) {
        Boolean currentFullScreen = isFullscreen;
        if (isFullscreen) {
            exitFullScreen(null, null);
        }
        if (callback != null) {
            callback.invoke(currentFullScreen);
        }
    }

    private boolean mControllerShow = true;
    /**
     * 显示控制面板
     */
    private final Runnable mShowControllerRunnable = () -> {
        if (!mControllerShow) {
            showController();
        }
    };

    /**
     * 隐藏控制面板
     */
    private final Runnable mHideControllerRunnable = () -> {
        if (mControllerShow) {
            hideController();
        }
    };

    /**
     * 显示面板
     */
    public void showController() {
        if (mControllerShow) {
            return;
        }
        mControllerShow = true;
        ObjectAnimator.ofFloat(mControlTopLayout, "translationY", -mControlTopLayout.getHeight(), 0).start();
        ObjectAnimator.ofFloat(mControlBottomLayout, "translationY", mControlBottomLayout.getHeight(), 0).start();
        ObjectAnimator.ofFloat(mControlRightLayout, "translationX", mControlRightLayout.getWidth() + mControlRightLayout.getResources().getDimension(R.dimen.padding_5), 0).start();

        ValueAnimator animator = ValueAnimator.ofFloat(0f, 1f);
        animator.setDuration(200);
        animator.addUpdateListener(animation -> {
            float alpha = (float) animation.getAnimatedValue();
//            mControlLeftLayout.setAlpha(alpha);

            if ((int) alpha != 1) {
                return;
            }
//            if (mControlLeftLayout.getVisibility() == INVISIBLE) {
//                mControlLeftLayout.setVisibility(VISIBLE);
//            }
        });
        animator.start();
    }


    /**
     * 隐藏面板
     */
    public void hideController() {
        if (!mControllerShow) {
            return;
        }
        mControllerShow = false;
        ObjectAnimator.ofFloat(mControlTopLayout, "translationY", 0, -mControlTopLayout.getHeight()).start();
        ObjectAnimator.ofFloat(mControlBottomLayout, "translationY", 0, mControlBottomLayout.getHeight()).start();
        ObjectAnimator.ofFloat(mControlRightLayout, "translationX", 0, mControlRightLayout.getWidth() + mControlRightLayout.getResources().getDimension(R.dimen.padding_5)).start();
        ValueAnimator animator = ValueAnimator.ofFloat(1f, 0f);
        animator.setDuration(200);
        animator.addUpdateListener(animation -> {
            float alpha = (float) animation.getAnimatedValue();
//            mControlLeftLayout.setAlpha(alpha);
            if (alpha != 0f) {
                return;
            }

//            if (mControlLeftLayout.getVisibility() == VISIBLE) {
//                mControlLeftLayout.setVisibility(INVISIBLE);
//            }
        });
        /*隐藏倍数选择控件*/
        mControlMiddleSpeedLayout.setVisibility(GONE);
        animator.start();
    }


    /*进入全屏*/
    @JSMethod
    public void enterFullScreen(JSONObject options, JSCallback callback) {
        if (isFullscreen) return;
        isFullscreen = true;
        /*剥离视图*/
        vlcVout.detachViews();
        // 横屏
        activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
        /*隐藏导航栏*/
        hideNavigationBar();
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                /*进入全屏*/
                activity.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
                ViewGroup localViewGroup = (ViewGroup) activity.getWindow().getDecorView();
                ((ViewGroup) getParent().getHostView()).removeView(getHostView());
                FrameLayout.LayoutParams localLayoutParams = new FrameLayout.LayoutParams(-1, -1);

                DisplayMetrics displayMetrics = activity.getResources().getDisplayMetrics();
                int screenWidth = displayMetrics.widthPixels;
                int screenHeight = displayMetrics.heightPixels;

                /*设置图像比例*/
                mMediaPlayer.setAspectRatio(screenWidth + ":" + (screenHeight));
                localViewGroup.addView(getHostView(), localLayoutParams);
                adjustSurfaceView();
                if (callback != null) {
                    callback.invoke(isFullscreen);
                }
                /*显示顶部返回控件*/
                mTopBack.setVisibility(VISIBLE);
                fullControl.setImageResource(R.drawable.nur_ic_fangxiao);
            }
        }, 300);

    }

    /*退出全屏*/
    @JSMethod
    public void exitFullScreen(JSONObject options, JSCallback callback) {
        if (!isFullscreen) return;
        isFullscreen = false;
        // 竖屏
        activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT);
        showNavigationBar();
        vlcVout.detachViews();
        // 退出全屏
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
                ((ViewGroup) activity.getWindow().getDecorView()).removeView(getHostView());
                ViewGroup localViewGroup = (ViewGroup) getParent().getHostView();
                View localView = getHostView();
                localViewGroup.addView(localView, new FrameLayout.LayoutParams(-1, -1));

                /*设置视频比例*/
                int width = surfaceView.getWidth();
                int height = surfaceView.getHeight();
                mMediaPlayer.setAspectRatio(width + ":" + initVideoHeight);
                adjustSurfaceView();
                if (callback != null) {
                    callback.invoke(isFullscreen);
                }
                /*隐藏顶部返回控件*/
                mTopBack.setVisibility(GONE);
                fullControl.setImageResource(R.drawable.nur_ic_fangda);
            }
        }, 300);
    }

    // 隐藏导航栏
    public void hideNavigationBar() {

        View decorView = activity.getWindow().getDecorView();
        int uiOptions = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_FULLSCREEN;
        decorView.setSystemUiVisibility(uiOptions);

//        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
//            activity.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
//                    WindowManager.LayoutParams.FLAG_FULLSCREEN);
//        } else {
//            View decorView = activity.getWindow().getDecorView();
//            activity.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
//                    WindowManager.LayoutParams.FLAG_FULLSCREEN);
//            int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
//                    | View.SYSTEM_UI_FLAG_IMMERSIVE | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
//            decorView.setSystemUiVisibility(uiOptions);
//        }
    }

    // 显示导航栏
    public void showNavigationBar() {
        activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        View decorView = activity.getWindow().getDecorView();
        int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_IMMERSIVE
                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_VISIBLE;
        decorView.setSystemUiVisibility(uiOptions);
//        View decorView = activity.getWindow().getDecorView();
//        int uiOptions = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
//                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
//                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN;
//        decorView.setSystemUiVisibility(uiOptions);
//        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
//            activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
//        } else {
//            View decorView = activity.getWindow().getDecorView();
//            activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
//            int uiOptions = View.SYSTEM_UI_FLAG_VISIBLE | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
//            decorView.setSystemUiVisibility(uiOptions);
//        }
    }

    //    调整播放器视图
    public void adjustSurfaceView() {
//        vlcVout.detachViews();
        surfaceView.post(new Runnable() {
            @Override
            public void run() {
                // 在子线程中准备播放
                int width = surfaceView.getWidth();
                int height = surfaceView.getHeight();
                vlcVout.setVideoSurface(surfaceView.getHolder().getSurface(), surfaceView.getHolder());
                vlcVout.setWindowSize(width, height);
                vlcVout.attachViews();
                surfaceView.requestLayout();
                mMediaPlayer.setTime(mMediaPlayer.getTime()+1000);
//                vlcContainerView.requestLayout();
                System.out.println("width ----" + width + " height ---" + height);
//                mMediaPlayer.setAspectRatio(width + ":" + height);
            }
        });
    }

    @JSMethod
    public void setPlayerTitle(JSONObject paramJSONObject) {
        String title = paramJSONObject.getString("title");
        mTitle = title;
        mTopTitle.setText(mTitle + "");
    }

    // 暂停
    @JSMethod
    public void pause(JSONObject options, JSCallback callback) {
        isPlay = false;
        if (mMediaPlayer != null) {
            mMediaPlayer.pause();
            isPlay = false;
        }
    }

    // 播放
    @UniJSMethod(uiThread = false)
    public void toPlay() {
        MediaPlayer localMediaPlayer = this.mMediaPlayer;
        if (localMediaPlayer != null) {
            localMediaPlayer.play();
            isPlay = true;
        }
    }

    // 终止
    @UniJSMethod(uiThread = false)
    public void stop() {
        mMediaPlayer.stop();
    }

    // 设置播放速率
    @JSMethod
    public void setRate(JSONObject paramJSONObject) {
        float rate = paramJSONObject.getFloatValue("rate");
        this.mMediaPlayer.setRate(rate);
    }

    /*设置播放地址*/
    @UniJSMethod(uiThread=false)
    public void setUrl(JSONObject paramJSONObject) throws MalformedURLException {
        String path = paramJSONObject.getString("url");
        play(path);
    }

    // 生命周期方法
    @Override
    public void onActivityStart() {
        super.onActivityStart();
    }

    // 其他生命周期方法
    @Override
    public void onActivityStop() {
        super.onActivityStop();
        this.mMediaPlayer.stop();
        mPlayBtn.setImageResource(R.drawable.player_play);
//        this.vlcVout.detachViews();
    }

    //    进入应用
    @Override
    public void onActivityResume() {
        super.onActivityResume();
//        this.mMediaPlayer.play();
        adjustSurfaceView();
    }

    //    应用在后台
    @Override
    public void onActivityPause() {
        super.onActivityPause();
        this.mMediaPlayer.pause();
//        this.vlcVout.detachViews();
    }

    @JSMethod
    public void destroyBehavior() {
        mMediaPlayer.release();
        mLibVLC.release();
        // 在销毁时禁用方向监听器
        orientationEventListener.disable();
    }
    @Override
    public void onActivityDestroy() {
        super.onActivityDestroy();
        destroyBehavior();
    }

    void callbackEvent(String paramString, Map paramMap) {
        int size = getEvents().size();
        int startNum = 0;
        int v;
        for (int i = 0; ; i++) {
            v = startNum;
            if (i >= size)
                break;
            if (!((String) getEvents().get(i)).equals(paramString))
                continue;
            v = 1;
            break;
        }
        if (v != 0) {
            HashMap localHashMap = new HashMap();
            if (paramMap != null)
                localHashMap.put("data", paramMap);
            fireEvent(paramString, localHashMap);
        }
    }

    private void log(String paramString) {
        Log.e("VlcPlugin", paramString);
    }

    private String getVideoFomatTime(long milliseconds) {
//        long milliseconds = paramEvent.getLengthChanged(); // 这是VLC返回的时长值
        // 将毫秒转换为秒
        long seconds = milliseconds / 1000;

        // 计算小时、分钟和秒
        int hours = (int) (seconds / 3600);
        int minutes = (int) ((seconds % 3600) / 60);
        int remainingSeconds = (int) (seconds % 60);

        // 构建时间字符串
        return String.format("%02d:%02d:%02d", hours, minutes, remainingSeconds);
    }

    private String totalTimeFormat;

    public void videoPlayerEvent(MediaPlayer.Event paramEvent) {
        int eventType = paramEvent.type;
        switch (eventType) {
            case MediaPlayer.Event.MediaChanged:
                log("MediaChanged");
                break;
            case MediaPlayer.Event.Opening:
                callbackEvent("onOpening", null);
                break;
            case MediaPlayer.Event.Stopped:
                if (mediaListenerEvent != null)
//                    handlerMsgShowHidePlayLoadingView(EnumConfig.PlayerState.PLAYER_SHOW_ERROR_VIEW);
                callbackEvent("onPlayStopped", null);
                break;
            case MediaPlayer.Event.Playing:
                callbackEvent("onPlaying", null);
                break;
            case MediaPlayer.Event.Paused:
                callbackEvent("onPlayPaused", null);
                break;
            case MediaPlayer.Event.EncounteredError:
                if (mediaListenerEvent != null)
                    mediaListenerEvent.eventError(MediaListenerEvent.EVENT_ERROR, true);
                callbackEvent("onPlayError", null);
                break;
            case MediaPlayer.Event.Buffering:
                if (mediaListenerEvent != null)
                    mediaListenerEvent.eventBuffing(MediaListenerEvent.EVENT_BUFFING, paramEvent.getBuffering());
                callbackEvent("Buffering", null);
                break;
            case MediaPlayer.Event.TimeChanged: // 播放中
                Map<String, Object> timeChangedMap = new HashMap<>();
                long currentMilliseconds = paramEvent.getTimeChanged(); // 这是VLC返回的时长值
                String currentTimeFormat = getVideoFomatTime(currentMilliseconds);
                timeChangedMap.put("time", Long.valueOf(currentMilliseconds));
                timeChangedMap.put("currentTimeFormat", currentTimeFormat);
                callbackEvent("onTimeChanged", timeChangedMap);

                vlcDuration.setText(currentTimeFormat + " / " + totalTimeFormat);
                vlcSeekbar.setProgress((int) (mMediaPlayer.getPosition() * 100));
                break;
            case MediaPlayer.Event.PositionChanged:
                Map<String, Object> positionChangedMap = new HashMap<>();
                positionChangedMap.put("position", Float.valueOf(paramEvent.getPositionChanged()));
                callbackEvent("onPositionChange", positionChangedMap);
                break;
            case MediaPlayer.Event.SeekableChanged:
                log("SeekableChanged: " + paramEvent.getSeekable());
                break;
            case MediaPlayer.Event.PausableChanged:
                log("PausableChanged: " + paramEvent.getPausable());
                break;
            case MediaPlayer.Event.ESAdded:
                callbackEvent("ESAdded", null);
                break;
            case MediaPlayer.Event.ESDeleted:
                callbackEvent("ESDeleted", null);
                break;
            case MediaPlayer.Event.ESSelected:
                callbackEvent("ESSelected", null);
                break;
            case MediaPlayer.Event.LengthChanged: // 获取视频总时长
                Map<String, Object> lengthChangedMap = new HashMap<>();
                long milliseconds = paramEvent.getLengthChanged(); // 这是VLC返回的时长值
                totalTimeFormat = getVideoFomatTime(milliseconds);
                lengthChangedMap.put("time", Long.valueOf(milliseconds));
                lengthChangedMap.put("totalTimeFormat", totalTimeFormat);
                callbackEvent("onTotalTime", lengthChangedMap);
                isFirstPlay = false;
                break;
            case MediaPlayer.Event.EndReached:
                mMediaPlayer.stop();
                callbackEvent("onPlayEnd", null);
                break;
            case MediaPlayer.Event.RecordChanged:
                log("RecordChanged: " + paramEvent.getRecordPath());
                break;
            case MediaPlayer.Event.Vout:
                log("Vout: " + paramEvent.getVoutCount());
                break;
            default:
                // Handle other event types or ignore them
                break;
        }
    }


}